// SilverBarter RPC Enums
enum SilverERPC
{
	SILVERRPC_SYNCH_TRADER_POINT_CLIENT,
	SILVERRPC_SYNCH_TRADER_POINT_SERVER
};

enum SilverRPC
{
	SILVERRPC_OPEN_TRADE_MENU,
	SILVERRPC_CLOSE_TRADER_MENU,
	SILVERRPC_ACTION_TRADER,
	SILVERRPC_SCREEN_MESSAGE,
	SILVERRPC_ROTATING_TRADER_SYNC
};
